

# This file was *autogenerated* from the file spryped.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12)
var('q1,q2,q3,q4,L1,L2,L3,L4,l1,l2,l3,l4')

T1_0 = matrix([[_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ],
     	       [_sage_const_0 , cos(q1), -sin(q1), L1*cos(q1)],
	       [_sage_const_0 , sin(q1), cos(q1), L1*sin(q1)],
	       [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])
	       
T2_1 = matrix([[cos(q2), -sin(q2), _sage_const_0 , L2*sin(q2)],
               [sin(q2), cos(q2), _sage_const_0 , L2*cos(q2)],
	       [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ],
	       [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])

T3_2 = matrix([[cos(q3), -sin(q3), _sage_const_0 , L3*sin(q3)],
               [sin(q3), cos(q3), _sage_const_0 , L3*cos(q3)],
	       [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ],
	       [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])

T4_3 = matrix([[cos(q4), -sin(q4), _sage_const_0 , L4*sin(q4)],
               [sin(q4), cos(q4), _sage_const_0 , L4*cos(q4)],
	       [_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ],
	       [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])

com1 = matrix([[_sage_const_0 ],
               [l1*cos(q1)],
               [l1*sin(q1)],
	       [_sage_const_1 ]])

com2 = matrix([[l2*sin(q2)],
               [l2*cos(q2)],
               [_sage_const_0 ],
	       [_sage_const_1 ]])

com3 = matrix([[l3*sin(q3)],
               [l3*cos(q3)],
               [_sage_const_0 ],
	       [_sage_const_1 ]])

com4 = matrix([[l4*sin(q4)],
               [l4*cos(q4)],
               [_sage_const_0 ],
	       [_sage_const_1 ]])

#Tcom1 = T1_0*com1 # unsimplified
Tcom1 = matrix([[_sage_const_0 ], # simplified manually
                [l1*cos(_sage_const_2 *q1) + L1*cos(q1)], # trig identity
                [l1*sin(_sage_const_2 *q1) + L1*sin(q1)], # trig identity
                [_sage_const_1 ]])
# Tcom1.apply_map(attrcall('trig_reduce'))

J1 = block_matrix([[Tcom1.derivative(q1), Tcom1.derivative(q2), Tcom1.derivative(q3)]], subdivide=False)

T2_0 = T1_0*T2_1

#Tcom2 = T2_0*com2 # unsimplified
Tcom2 = matrix([[L2*sin(q2)], # simplified manually
                [cos(q1)*(l2 + L1 + L2*cos(q2))], # trig identity
                [sin(q1)*(l2 + L1 + L2*cos(q2))], # trig identity
                [_sage_const_1 ]])

J2 = block_matrix([[Tcom2.derivative(q1), Tcom2.derivative(q2), Tcom2.derivative(q3)]], subdivide=False)

#T3_0 = T3_2*T2_1*T1_0 # unsimplified
T3_0 = matrix([[cos(q2+q3), -sin(q2+q3)*cos(q1), sin(q2+q3)*sin(q1), sin(q2+q3)*L1*cos(q1) + L2*sin(q2-q3) + L3*sin(q3)], # simplified manually
               [sin(q2+q3), cos(q2+q3)*cos(q1), -cos(q2+q3)*sin(q1), sin(q2+q3)*L1*cos(q1) + L2*cos(q2-q3) + L3*cos(q3)],
               [_sage_const_0 , sin(q1), cos(q1), L1*sin(q1)],
               [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]])
Tcom3 = T3_0*com3 # unsimplified

J3 = block_matrix([[Tcom3.derivative(q1), Tcom3.derivative(q2), Tcom3.derivative(q3)]], subdivide=False)

T4_0 = T4_3*T3_2*T2_1*T1_0

Tcom4 = T4_0*com4
Tcom4simp = matrix([[-sin(q2+q3+q4)*(l4*cos(q1)*cos(q4)+L1*cos(q1)+L2)+L3*sin(q3-q4)+cos(q2+q3+q4)*l4*sin(q4)+L4*sin(q4)],
                    [cos(q2+q3+q4)*(l4*cos(q1)*cos(q4)+L1*cos(q1))+cos(q3+q4-q2)*L2+L3*cos(q3-q4)+sin(q2+q3+q4)*l4*sin(q4)+L4*cos(q4)],
                    [l4*cos(q4)*sin(q1) + L1*sin(q1)],
                    [_sage_const_1 ]])
J4 = block_matrix([[Tcom4.derivative(q1), Tcom4.derivative(q2), Tcom4.derivative(q3), Tcom4.derivative(q4)]], subdivide=False)

print(Tcom4(q1=_sage_const_1 ,q2=_sage_const_2 ,q3=_sage_const_3 ,q4=_sage_const_4 ,l1=_sage_const_5 ,l2=_sage_const_6 ,l3=_sage_const_7 ,l4=_sage_const_8 ,L1=_sage_const_9 ,L2=_sage_const_10 ,L3=_sage_const_11 ,L4=_sage_const_12 ))
print(Tcom4simp(q1=_sage_const_1 ,q2=_sage_const_2 ,q3=_sage_const_3 ,q4=_sage_const_4 ,l1=_sage_const_5 ,l2=_sage_const_6 ,l3=_sage_const_7 ,l4=_sage_const_8 ,L1=_sage_const_9 ,L2=_sage_const_10 ,L3=_sage_const_11 ,L4=_sage_const_12 ))
#print("Tcom4 = ", Tcom4)
#print("Tcom4 simplified = ", Tcom4simp)

